"""drop severity column

Revision ID: d574cbece39b
Revises: f7b9c71ee413
Create Date: 2025-11-23 18:07:04.512107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd574cbece39b'
down_revision: Union[str, Sequence[str], None] = 'f7b9c71ee413'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sightings', 'severity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sightings', sa.Column('severity', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
